In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('wine.csv')
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values
print ("Dataset :")
print (dataset)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

Dataset :
     Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..    ...      ...         ...   ...   ...  ...      ...         ...   
173     3    13.71        5.65  2.45  20.5   95     1.68        0.61   
174     3    13.40        3.91  2.48  23.0  102     1.80        0.75   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.9

In [2]:
# Naive Bayes

# Fitting the classifier to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set reults
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_n = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix (Naive Bayes) :")
print (cm_n)

Confusion Matrix (Naive Bayes) :
[[16  0  0]
 [ 2 18  1]
 [ 0  0  8]]


In [3]:
# Decision Tree Classification

# Fitting classifier to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_e = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix (Decision Trees [Entropy]) :")
print (cm_e)

Confusion Matrix (Decision Trees [Entropy]) :
[[15  1  0]
 [ 1 19  1]
 [ 0  0  8]]


In [4]:
# Decision Tree Classification

# Fitting classifier to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_g = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix (Decision Trees [Gini]) :")
print (cm_g)

Confusion Matrix (Decision Trees [Gini]) :
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


In [5]:
# Accuracy

# Naive Bayes
print ("Accuracy for Naive Bayes:")
n = 0
for i in range(len(cm_n[0])):
    n = n + cm_n[i][i]
acc = n/sum(sum(cm_n))
print(acc*100)

# Decision Tree (Entropy)
print ("\nAccuracy for Decision Tree (Entropy):")
n = 0
for i in range(len(cm_e[0])):
    n = n + cm_e[i][i]
acc = n/sum(sum(cm_e))
print(acc*100)

# Decision Tree (Gini)
print ("\nAccuracy for Decision Tree (Gini):")
n = 0
for i in range(len(cm_g[0])):
    n = n + cm_g[i][i]
acc = n/sum(sum(cm_g))
print(acc*100)

Accuracy for Naive Bayes:
93.33333333333333

Accuracy for Decision Tree (Entropy):
93.33333333333333

Accuracy for Decision Tree (Gini):
93.33333333333333
